zephyr_include_directories(include)
zephyr_include_directories(include/sodium)
zephyr_include_directories(include/sodium/private)
add_subdirectory(sodium)
add_subdirectory(randombytes)
add_subdirectory(crypto_hash)
add_subdirectory(crypto_pwhash)
add_subdirectory(crypto_aead)
add_subdirectory(crypto_auth)
add_subdirectory(crypto_box)
add_subdirectory(crypto_core)
add_subdirectory(crypto_generichash)
add_subdirectory(crypto_kx)
add_subdirectory(crypto_kdf)
add_subdirectory(crypto_onetimeauth)
add_subdirectory(crypto_scalarmult)
add_subdirectory(crypto_secretbox)
add_subdirectory(crypto_shorthash)
add_subdirectory(crypto_sign)
add_subdirectory(crypto_stream)
add_subdirectory(crypto_verify)

